CREATE TABLE HC_BUREAU (
    SK_ID_BUREAU      NUMBER NOT NULL,
    SK_ID_CURR        NUMBER NOT NULL,
    CREDIT_ACTIVE     VARCHAR2(50),
    CREDIT_CURRENCY   VARCHAR2(50),
    DAYS_CREDIT       NUMBER,
    CREDIT_DAY_OVERDUE NUMBER,
    DAYS_CREDIT_ENDDATE NUMBER,
    DAYS_ENDDATE_FACT NUMBER,
    AMT_CREDIT_MAX_OVERDUE NUMBER(18,2),
    CNT_CREDIT_PROLONG NUMBER,
    AMT_CREDIT_SUM NUMBER(18,2),
    AMT_CREDIT_SUM_DEBT NUMBER(18,2),
    AMT_CREDIT_SUM_LIMIT NUMBER(18,2),
    AMT_CREDIT_SUM_OVERDUE NUMBER(18,2),
    CREDIT_TYPE VARCHAR2(100),
    DAYS_CREDIT_UPDATE NUMBER,

    CONSTRAINT PK_HC_BUREAU PRIMARY KEY (SK_ID_BUREAU),
    CONSTRAINT FK_HC_BUREAU_APP FOREIGN KEY (SK_ID_CURR)
        REFERENCES HC_APPLICATION(SK_ID_CURR)
);