CREATE TABLE HC_CREDIT_CARD_BALANCE (
    SK_ID_PREV NUMBER NOT NULL,
    SK_ID_CURR NUMBER NOT NULL,
    MONTHS_BALANCE NUMBER NOT NULL,
    AMT_BALANCE NUMBER(18,2),
    AMT_CREDIT_LIMIT_ACTUAL NUMBER(18,2),
    AMT_DRAWINGS_CURRENT NUMBER(18,2),
    AMT_PAYMENT_CURRENT NUMBER(18,2),
    AMT_TOTAL_RECEIVABLE NUMBER(18,2),
    NAME_CONTRACT_STATUS VARCHAR2(50),
    SK_DPD NUMBER,
    SK_DPD_DEF NUMBER,
    CONSTRAINT PK_HC_CC_BALANCE PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE),
    CONSTRAINT FK_HC_CC_PREV FOREIGN KEY (SK_ID_PREV)
        REFERENCES HC_PREVIOUS_APPLICATION(SK_ID_PREV)
);