CREATE TABLE FT_BUREAU AS
SELECT
    SK_ID_CURR,
    COUNT(*) AS QTD_CREDITOS_BUREAU,
    SUM(AMT_CREDIT_SUM_DEBT) AS TOTAL_DIVIDA_BUREAU,
    AVG(CREDIT_DAY_OVERDUE) AS MEDIA_DIAS_ATRASO_BUREAU
FROM HC_BUREAU
GROUP BY SK_ID_CURR;

---------------------------------------------

CREATE TABLE FT_PREVIOUS AS
SELECT
    SK_ID_CURR,
    COUNT(*) AS QTD_APLICACOES_ANTERIORES,
    SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Refused' THEN 1 ELSE 0 END) AS QTD_RECUSAS_ANTERIORES
FROM HC_PREVIOUS_APPLICATION
GROUP BY SK_ID_CURR;

---------------------------------------------


CREATE TABLE FT_INSTALLMENTS AS
SELECT
    SK_ID_CURR,
    AVG(DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT) AS ATRASO_MEDIO_PAGAMENTO,
    SUM(CASE 
        WHEN DAYS_ENTRY_PAYMENT > DAYS_INSTALMENT THEN 1 
        ELSE 0 
    END) AS QTD_PARCELAS_ATRASADAS
FROM HC_INSTALLMENTS_PAYMENTS
GROUP BY SK_ID_CURR;

---------------------------------------------

CREATE TABLE HC_MODEL_FEATURES AS
SELECT
    A.SK_ID_CURR,
    A.TARGET,
    A.NAME_CONTRACT_TYPE,
    A.CODE_GENDER,
    A.AMT_INCOME_TOTAL,
    A.AMT_CREDIT,
    A.AMT_ANNUITY,
    A.DAYS_BIRTH,
    A.DAYS_EMPLOYED,

    B.QTD_CREDITOS_BUREAU,
    B.TOTAL_DIVIDA_BUREAU,
    B.MEDIA_DIAS_ATRASO_BUREAU,

    P.QTD_APLICACOES_ANTERIORES,
    P.QTD_RECUSAS_ANTERIORES,

    I.ATRASO_MEDIO_PAGAMENTO,
    I.QTD_PARCELAS_ATRASADAS

FROM HC_APPLICATION A
LEFT JOIN FT_BUREAU B
    ON A.SK_ID_CURR = B.SK_ID_CURR
LEFT JOIN FT_PREVIOUS P
    ON A.SK_ID_CURR = P.SK_ID_CURR
LEFT JOIN FT_INSTALLMENTS I
    ON A.SK_ID_CURR = I.SK_ID_CURR
WHERE A.DATASET_TYPE = 'TRAIN';

---------------------------------------------

SELECT * FROM HC_MODEL_FEATURES