CREATE INDEX IDX_HC_BUREAU_CURR ON HC_BUREAU(SK_ID_CURR);
CREATE INDEX IDX_HC_PREV_CURR ON HC_PREVIOUS_APPLICATION(SK_ID_CURR);
CREATE INDEX IDX_HC_POS_CURR ON HC_POS_CASH_BALANCE(SK_ID_CURR);
CREATE INDEX IDX_HC_INST_CURR ON HC_INSTALLMENTS_PAYMENTS(SK_ID_CURR);
CREATE INDEX IDX_HC_CC_CURR ON HC_CREDIT_CARD_BALANCE(SK_ID_CURR);