CREATE TABLE HC_APPLICATION (
    SK_ID_CURR        NUMBER NOT NULL,
    DATASET_TYPE      VARCHAR2(10) NOT NULL,
    TARGET            NUMBER(1),
    NAME_CONTRACT_TYPE VARCHAR2(50),
    CODE_GENDER       VARCHAR2(10),
    FLAG_OWN_CAR      VARCHAR2(5),
    FLAG_OWN_REALTY   VARCHAR2(5),
    CNT_CHILDREN      NUMBER,
    AMT_INCOME_TOTAL  NUMBER(18,2),
    AMT_CREDIT        NUMBER(18,2),
    AMT_ANNUITY       NUMBER(18,2),
    AMT_GOODS_PRICE   NUMBER(18,2),
    NAME_INCOME_TYPE  VARCHAR2(100),
    NAME_EDUCATION_TYPE VARCHAR2(100),
    NAME_FAMILY_STATUS VARCHAR2(100),
    NAME_HOUSING_TYPE VARCHAR2(100),
    DAYS_BIRTH        NUMBER,
    DAYS_EMPLOYED     NUMBER,
    OCCUPATION_TYPE   VARCHAR2(100),
    REGION_RATING_CLIENT NUMBER,
    EXT_SOURCE_1      NUMBER(18,8),
    EXT_SOURCE_2      NUMBER(18,8),
    EXT_SOURCE_3      NUMBER(18,8),
    CONSTRAINT PK_HC_APPLICATION PRIMARY KEY (SK_ID_CURR),
    CONSTRAINT CK_HC_APP_DATASET CHECK (DATASET_TYPE IN ('TRAIN', 'TEST')),
    CONSTRAINT CK_HC_APP_TARGET CHECK (TARGET IN (0, 1) OR TARGET IS NULL)
);

SELECT COUNT(*) FROM HC_APPLICATION;
SELECT COUNT(*) FROM HC_BUREAU;
SELECT COUNT(*) FROM HC_BUREAU_BALANCE;
SELECT COUNT(*) FROM HC_PREVIOUS_APPLICATION;
SELECT COUNT(*) FROM HC_POS_CASH_BALANCE;
SELECT COUNT(*) FROM HC_INSTALLMENTS_PAYMENTS;
SELECT COUNT(*) FROM HC_CREDIT_CARD_BALANCE;

COMMIT;

