CREATE TABLE HC_BUREAU_BALANCE (
    SK_ID_BUREAU NUMBER NOT NULL,
    MONTHS_BALANCE NUMBER NOT NULL,
    STATUS VARCHAR2(10),
    CONSTRAINT PK_HC_BUREAU_BALANCE PRIMARY KEY (SK_ID_BUREAU, MONTHS_BALANCE),
    CONSTRAINT FK_HC_BB_BUREAU FOREIGN KEY (SK_ID_BUREAU)
        REFERENCES HC_BUREAU(SK_ID_BUREAU)
);