CREATE TABLE HC_INSTALLMENTS_PAYMENTS (
    SK_ID_PREV NUMBER NOT NULL,
    SK_ID_CURR NUMBER NOT NULL,
    NUM_INSTALMENT_VERSION NUMBER,
    NUM_INSTALMENT_NUMBER NUMBER NOT NULL,
    DAYS_INSTALMENT NUMBER,
    DAYS_ENTRY_PAYMENT NUMBER,
    AMT_INSTALMENT NUMBER(18,2),
    AMT_PAYMENT NUMBER(18,2),
    CONSTRAINT PK_HC_INSTALLMENTS PRIMARY KEY 
        (SK_ID_PREV, NUM_INSTALMENT_NUMBER),
    CONSTRAINT FK_HC_INST_PREV FOREIGN KEY (SK_ID_PREV)
        REFERENCES HC_PREVIOUS_APPLICATION(SK_ID_PREV)
);