CREATE TABLE HC_POS_CASH_BALANCE (
    SK_ID_PREV NUMBER NOT NULL,
    SK_ID_CURR NUMBER NOT NULL,
    MONTHS_BALANCE NUMBER NOT NULL,
    CNT_INSTALMENT NUMBER,
    CNT_INSTALMENT_FUTURE NUMBER,
    NAME_CONTRACT_STATUS VARCHAR2(50),
    SK_DPD NUMBER,
    SK_DPD_DEF NUMBER,
    CONSTRAINT PK_HC_POS PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE),
    CONSTRAINT FK_HC_POS_PREV FOREIGN KEY (SK_ID_PREV)
        REFERENCES HC_PREVIOUS_APPLICATION(SK_ID_PREV)
);