CREATE TABLE HC_PREVIOUS_APPLICATION (
    SK_ID_PREV NUMBER NOT NULL,
    SK_ID_CURR NUMBER NOT NULL,
    NAME_CONTRACT_TYPE VARCHAR2(50),
    AMT_ANNUITY NUMBER(18,2),
    AMT_APPLICATION NUMBER(18,2),
    AMT_CREDIT NUMBER(18,2),
    AMT_DOWN_PAYMENT NUMBER(18,2),
    NAME_CONTRACT_STATUS VARCHAR2(50),
    DAYS_DECISION NUMBER,
    CODE_REJECT_REASON VARCHAR2(50),
    NAME_CLIENT_TYPE VARCHAR2(50),
    NAME_PRODUCT_TYPE VARCHAR2(50),
    CHANNEL_TYPE VARCHAR2(100),
    CONSTRAINT PK_HC_PREVIOUS_APPLICATION PRIMARY KEY (SK_ID_PREV),
    CONSTRAINT FK_HC_PREV_APP FOREIGN KEY (SK_ID_CURR)
        REFERENCES HC_APPLICATION(SK_ID_CURR)
);