-- INADIMPLENCIA POR CONTATO -- 

SELECT
    NAME_CONTRACT_TYPE,
    COUNT(*) AS TOTAL_CLIENTES,
    SUM(TARGET) AS TOTAL_INADIMPLENTES,
    ROUND(AVG(TARGET) * 100, 2) AS TAXA_INADIMPLENCIA_PCT
FROM HC_APPLICATION
WHERE DATASET_TYPE = 'TRAIN'
GROUP BY NAME_CONTRACT_TYPE
ORDER BY TAXA_INADIMPLENCIA_PCT DESC;

-- INADIMPLENCIA POR FAIXA DE RENDA -- 

SELECT
    CASE
        WHEN AMT_INCOME_TOTAL < 100000 THEN '01 - Até 100k'
        WHEN AMT_INCOME_TOTAL < 200000 THEN '02 - 100k a 200k'
        WHEN AMT_INCOME_TOTAL < 400000 THEN '03 - 200k a 400k'
        ELSE '04 - Acima de 400k'
    END AS FAIXA_RENDA,
    COUNT(*) AS TOTAL_CLIENTES,
    ROUND(AVG(TARGET) * 100, 2) AS TAXA_INADIMPLENCIA_PCT
FROM HC_APPLICATION
WHERE DATASET_TYPE = 'TRAIN'
GROUP BY
    CASE
        WHEN AMT_INCOME_TOTAL < 100000 THEN '01 - Até 100k'
        WHEN AMT_INCOME_TOTAL < 200000 THEN '02 - 100k a 200k'
        WHEN AMT_INCOME_TOTAL < 400000 THEN '03 - 200k a 400k'
        ELSE '04 - Acima de 400k'
    END
ORDER BY FAIXA_RENDA;

-- ATRASO MEDIO DE PAGAMENTO POR FAIXA DE RENDA -- 

SELECT
    CASE
        WHEN A.AMT_INCOME_TOTAL < 100000 THEN '01 - Até 100k'
        WHEN A.AMT_INCOME_TOTAL < 200000 THEN '02 - 100k a 200k'
        WHEN A.AMT_INCOME_TOTAL < 400000 THEN '03 - 200k a 400k'
        ELSE '04 - Acima de 400k'
    END AS FAIXA_RENDA,
    ROUND(AVG(I.DAYS_ENTRY_PAYMENT - I.DAYS_INSTALMENT), 2) AS ATRASO_MEDIO_DIAS,
    COUNT(*) AS TOTAL_PARCELAS
FROM HC_APPLICATION A
JOIN HC_INSTALLMENTS_PAYMENTS I
    ON A.SK_ID_CURR = I.SK_ID_CURR
WHERE A.DATASET_TYPE = 'TRAIN'
  AND I.DAYS_ENTRY_PAYMENT IS NOT NULL
  AND I.DAYS_INSTALMENT IS NOT NULL
GROUP BY
    CASE
        WHEN A.AMT_INCOME_TOTAL < 100000 THEN '01 - Até 100k'
        WHEN A.AMT_INCOME_TOTAL < 200000 THEN '02 - 100k a 200k'
        WHEN A.AMT_INCOME_TOTAL < 400000 THEN '03 - 200k a 400k'
        ELSE '04 - Acima de 400k'
    END
ORDER BY FAIXA_RENDA;

-- CLIENTES COM MAIOR EXPOSIÇÃO A CREDITOS NO BUREAU -- 

SELECT
    A.SK_ID_CURR,
    A.TARGET,
    A.AMT_INCOME_TOTAL,
    SUM(B.AMT_CREDIT_SUM) AS TOTAL_CREDITO_BUREAU,
    SUM(B.AMT_CREDIT_SUM_DEBT) AS TOTAL_DIVIDA_BUREAU,
    ROUND(SUM(B.AMT_CREDIT_SUM_DEBT) / NULLIF(A.AMT_INCOME_TOTAL, 0), 2) AS DEBT_TO_INCOME
FROM HC_APPLICATION A
JOIN HC_BUREAU B
    ON A.SK_ID_CURR = B.SK_ID_CURR
WHERE A.DATASET_TYPE = 'TRAIN'
GROUP BY
    A.SK_ID_CURR,
    A.TARGET,
    A.AMT_INCOME_TOTAL
ORDER BY DEBT_TO_INCOME DESC;